use db_didh2
GO
SET IDENTITY_INSERT Recommendations ON 
INSERT INTO Recommendations (Id,Nom,NomAr,CodeRecommendation,CodeRecommendationAr,Mecanisme,IdCycle,Axes,SousAxes,IdOrgane,IdVisite,IdPays,Etat,EtatAvancement,EtatAvancementChiffre,Observation,Complement,PieceJointe,Annee) values
(300, N'Le Groupe de travail est convaincu que l’indépendance et l’impartialité du pouvoir judiciaire sont essentielles pour prévenir les disparitions forcées et punir de façon efficace leurs auteurs.', N'', N'R92', N'', N'Procédure spéciale', null, '[1]', '[1]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'Réalisé', '', 100, '', '', '', 2020),
(301, N'Le Groupe de travail observe que l’actuelle procédure pénale offre déjà d’importantes garanties contre la détention arbitraire et la disparition forcée dont, notamment, les dispositions relatives à la garde à vue, l’obligation pour le procureur d’informer la famille du détenu, la compétence reconnue au procureur et au juge d’instruction pour visiter des centres de détention et vérifier la légalité et les conditions de détention, et l’obligation de tenir des registres officiels sur les détentions.Toutefois, le Groupe de travail a reçu des allégations selon lesquelles ces dispositions n’étaient pas toujours appliquées. La mise en œuvre effective de ces garanties est donc prioritaire.', N'', N'R99', N'', N'Procédure spéciale', null, '[1]', '[1]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(302, N'Le Groupe de travail attend avec impatience la ratification par le Maroc de la Convention internationale pour la protection de toutes les personnes contre les disparitions forcées et sa reconnaissance de la compétence du Comité au titre des articles 31 et 32 de la Convention, de même que la ratification d’autres instruments internationaux qui ont une incidence sur la disparition forcée.', N'', N'R102', N'', N'Procédure spéciale', null, '[2]', '[5]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(303, N'Le Maroc devrait ratifier le Protocole facultatif se rapportant au Pacte international relatif aux droits civils et politiques, le Comité des droits de l’homme ayant une jurisprudence bien établie dans le domaine des disparitions forcées.', N'', N'R103', N'', N'Procédure spéciale', null, '[2]', '[5]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'Non réalisé', '', 0, '', '', '', 2020),
(304, N'Le Groupe de travail appelle aussi le Maroc à ratifier le Statut de Rome sur la Cour pénale internationale qui qualifie la disparition forcée de crime contre l’humanité sous certaines conditions', N'', N'R 104', N'', N'Procédure spéciale', null, '[2]', '[5]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'Non réalisé', '', 0, '', '', '', 2020),
(305, N'Le Groupe de travail encourage aussi le Maroc à ratifier les Protocoles I et II aux Conventions de Genève du 12 août 1949, le Protocole I contenant des dispositions fondamentales sur la question des «personnes disparues» (art. 32 et suiv.).', N'', N'R105', N'', N'Procédure spéciale', null, '[2]', '[5]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'Réalisé', '', 100, '', '', '', 2020),
(306, N'Le Groupe de travail relève que certaines dispositions actuellement en vigueur dans le Code pénal ont un lien avec les disparitions forcées, mais qu’il n’existe pas d’article incriminant spécifiquement les disparitions forcées.
Le Groupe de travail prend note des informations fournies par des sources officielles selon lesquelles le nouveau Code pénal, actuellement en cours de rédaction, fait de la disparition forcée un crime autonome.', N'', N'R97', N'', N'Procédure spéciale', null, '[3]', '[9]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(307, N'Le Groupe de travail espère que le processus législatif devant aboutir à cet important objectif sera mené à bien, dans les plus brefs délais. Cependant, la loi concernée ne devra pas se restreindre à inclure une définition du crime, mais devra également:
a) Définir des peines proportionnées à l’extrême gravité de ce crime;
b) Respecter le principe selon lequel l’une des caractéristique essentielles de ce crime est son caractère continu;', N'', N'R98P1P2', N'', N'Procédure spéciale', null, '[3]', '[9]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(308, N'Le Groupe de travail est aussi convaincu que la législation devrait prévoir des garanties supplémentaires, en conformité avec les normes définies par les instruments internationaux. Parmi les mesures qui devraient être prises, le Groupe de travail voudrait mettre l’accent sur les suivantes:
• La privation de liberté d’une personne dans un endroit non officiel doit être Interdite et incriminée (art. 10 de la Déclaration).
• La loi doit reconnaître et appliquer «le droit à un recours rapide et efficace pour déterminer l’endroit où se trouve une personne privée de liberté ou son état de santé et/ou pour identifier l’autorité qui a ordonné la privation de liberté» (art. 9, par. 1, de la Déclaration) ainsi que l’obligation de rendre une décision sur la légalité de la privation de liberté (habeas corpus, conformément à l’article 17, par. 2 f), de la Convention internationale pour la protection de toutes les personnes contre les disparitions forcées).', N'', N'R100P1P2', N'', N'Procédure spéciale', null, '[3]', '[9]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(309, N'continuer à mettre la législation nationale en conformité avec ses obligations internationales en matière de droits de l’homme', N'', N'R89', N'', N'Procédure spéciale', null, '[3]', '[10]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(310, N'Le Groupe recommande que les normes internationales relatives aux disparitions forcées soient pleinement prises en considération dans ce processus.', N'', N'R96', N'', N'Procédure spéciale', null, '[3]', '[10]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(311, N'Se conformer aux dispositions du paragraphe 3 de l’article 17 de la Déclaration en vertu duquel «s’il y a prescription des actes conduisant à des disparitions forcées, le délai de prescription doit être de longue durée et en rapport avec l’extrême gravité du crime»', N'', N'R98P3', N'', N'Procédure spéciale', null, '[3]', '[10]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(312, N'Garantir que les responsables du crime de disparitions forcées «ne peuvent être jugés que par les juridictions de droit commun compétentes, dans chaque État, à l’exclusion de toute autre juridiction spéciale, notamment militaire» (art. 16,  par. 2, de la Déclaration)', N'', N'R98P4', N'', N'Procédure spéciale', null, '[3]', '[10]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'Réalisé', '', 100, '', '', '', 2020),
(313, N'Garantir «qu’aucun ordre ou instruction émanant d’aucune autorité publique, civile, militaire ou autre ne peut être invoqué pour justifier une disparition forcée. Toute personne recevant un tel ordre ou une telle instruction a le droit et le devoir de ne pas s’y conformer» (art. 6, par. 1, de la Déclaration).', N'', N'R98P5', N'', N'Procédure spéciale', null, '[3]', '[10]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(314, N'La loi doit établir la compétence des juridictions pénales civiles (et non militaires) pour traduire tout auteur présumé de disparition forcée, sur une base territoriale, personnelle mais aussi universelle (art. 14 de la Déclaration).', N'', N'R100P4', N'', N'Procédure spéciale', null, '[3]', '[10]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'Réalisé', '', 100, '', '', '', 2020),
(315, N'Des mesures d’ordre législatif effectives et toutes autres mesures appropriées doivent être prises pour mettre fin à l’impunité des auteurs, comme première étape afin d’assurer que les disparitions forcées ne se reproduiront pas à l’avenir.', N'', N'R108', N'', N'Procédure spéciale', null, '[5]', '[20]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(316, N'La loi doit garantir le pouvoir des «institutions nationales compétentes d’avoir accès à tous les lieux ou sont gardées des personnes privées de liberté et à toutes parties de ces lieux, ainsi qu’à tout autre lieu s’il y a des raisons de croire que les personnes disparues peuvent s’y trouver» (art. 9, par. 2, de la Déclaration).', N'', N'R100P3', N'', N'Procédure spéciale', null, '[5]', '[21]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'Réalisé', '', 100, '', '', '', 2020),
(317, N'Les corps trouvés dans des sépultures doivent être formellement identifiés et cette identification doit être pleinement acceptée par la famille de la victime.
Lorsque des doutes persistent, des analyses ADN doivent être réalisées.', N'', N'R106P2', N'', N'Procédure spéciale', null, '[5]', '[22]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(318, N'Le processus de mise en œuvre du programme de réparation communautaire doit être accéléré, dans le respect de l’approche participative prévue par l’IER,  impliquant en particulier les anciens disparus qui ont été détenus dans ces centres.', N'', N'R107P2', N'', N'Procédure spéciale', null, '[5]', '[22]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'Réalisé', '', 100, '', '', '', 2020),
(319, N'• Le CCDH devrait publier un rapport complet sur le suivi des recommandations de l’IER, incluant aussi une liste complète et détaillée des 742 cas de disparitions élucidés par l’IER et des 66 cas restés en suspens.', N'', N'R106P1', N'', N'Procédure spéciale', null, '[5]', '[26]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(320, N'Dans le cadre du suivi du travail de l’IER, le CCDH doit rendre publiques les archives de l’IER et tout autre document permettant de déterminer si des situations semblables ont toujours été traitées de façon égale, particulièrement en ce qui concerne les victimes originaires du Sahara occidental.', N'', N'R106P4', N'', N'Procédure spéciale', null, '[5]', '[26]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(321, N'Les chiffres concernant les mesures de réparation doivent être publiés et des rapports détaillés sur les mesures prises à ce jour doivent être rendus publics', N'', N'R107P1', N'', N'Procédure spéciale', null, '[5]', '[26]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(322, N'Le dossier complet de chaque victime doit être remis à la victime ou à sa famille.', N'', N'R106P7', N'', N'Procédure spéciale', null, '[5]', '[26]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(323, N'Les décisions arbitrales sur des indemnisations individuelles devraient être rendues publiques avec le consentement des victimes, et largement publiées de façon à ce que chacun ait la possibilité de vérifier et de commenter la  «jurisprudence» de la Commission d’arbitrage, de l’IER et du CCDH.', N'', N'R106P5', N'', N'Procédure spéciale', null, '[5]', '[26]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(324, N'Le Groupe de travail salue les mesures et les efforts du CCDH pour la rédaction d’un mémorandum sur la réforme de la gouvernance des appareils de sécurité et lui  de prendre en considération l’article 12 de la Déclaration sur la protection de toutes les personnes contre les disparitions forcées dans ledit mémorandum.', N'', N'R94', N'', N'Procédure spéciale', null, '[8]', '[]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'En cours', '', 30, '', '', '', 2020),
(325, N'Pour que le CCDH renforce le rôle crucial qu’il joue dans le suivi des activités de l’IER, le Groupe de travail suggère que l’indépendance du CCDH soit renforcée. À cette fin, le Groupe de travail considère qu’aucun membre du CCDH ne devrait être choisi par le Roi et qu’aucun ministère relevant du pouvoir exécutif du Gouvernement (par exemple le Ministère de la justice) ne devrait participer aux sessions du CCDH, pas même en tant que simple observateur ou avec un mandat consultatif.', N'', N'R95', N'', N'Procédure spéciale', null, '[8]', '[]', null, Groupe de travail sur les disparitions forcées ou involontaires, null, 'Non réalisé', '', 0, '', '', '', 2020),
(326, N'signer et ratifier la Convention relative aux droits des personnes handicapées', N'', N'R74P11-1', N'', N'Procédure spéciale', null, '[2]', '[5]', null, Rapporteur spécial sur le droit à l’éducation, null, 'Réalisé', '', 100, '', '', '', 2020),
(327, N'signer et ratifier le protocole facultatif à la Convention relative aux droits des personnes handicapées , et d’adopter un plan de transition vers un système éducatif inclusif;', N'', N'R74P11-2', N'', N'Procédure spéciale', null, '[2]', '[5]', null, Rapporteur spécial sur le droit à l’éducation, null, 'Non réalisé', '', 0, '', '', '', 2020),
(328, N'Mettre en place un système de protection juridique contre le harcèlement sexuel et les abus sexuels à l’encontre des élèves filles et adolescentes;', N'', N'R74P8', N'', N'Procédure spéciale', null, '[3,6]', '[9,32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(329, N'Promouvoir une modification de la législation en vigueur devant permettre l’inscription des enfants − filles et garçons − dans le système éducatif même sans le consentement de leur père ou mère', N'', N'R74P14', N'', N'Procédure spéciale', null, '[3,4,6]', '[9,12,14,32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(330, N'Rattraper le retard dans la réalisation des objectifs assignés à la Charte nationale d’éducation et de formation en matière d’enseignement de la langue et de la culture amazighes et introduire progressivement cet enseignement dans les écoles de l’ensemble du pays;', N'', N'R73P5', N'', N'Procédure spéciale', null, '[4]', '[12,14]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(331, N'mettre en place un plan adapté de formation à l’enseignement de l’amazigh à
l’intention des enseignants, en veillant à allonger à brève échéance la durée de la formation, en particulier pour les enseignants dont l’amazigh n’est pas la langue maternelle', N'', N'R74P10-1', N'', N'Procédure spéciale', null, '[4]', '[12,14]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(332, N'imposer à plus longue échéance pour l’enseignement de l’amazigh les mêmes exigences en matière de formation universitaire que pour les autres langues enseignées, telles que l’arabe, le français ou l’anglais', N'', N'R74P10-2', N'', N'Procédure spéciale', null, '[4,6]', '[12,14,32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(333, N'adopter un plan de transition vers un système éducatif inclusif;', N'', N'R74P11-3', N'', N'Procédure spéciale', null, '[4,6]', '[12,14,33]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(334, N'Renforcer la perspective du genre dans le système éducatif, ainsi que le principe d’égalité entre hommes et femmes, pour en finir avec la conception actuelle qui se borne à rechercher la parité entre filles et garçons en matière d’accès à l’éducation et à éliminer les stéréotypes sexistes dans les livres de textes.', N'', N'R73P8', N'', N'Procédure spéciale', null, '[4,6]', '[14,32,30]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(335, N'Inclure rapidement et de manière plus poussée dans l’éducation formelle et non formelle de larges pans de la population enfantine, avant tout les garçons et filles handicapés, en particulier ceux vivant en milieu rural, les garçons et filles de la rue et les garçons et filles qui travaillent. pas scolarisés', N'', N'R73P2', N'', N'Procédure spéciale', null, '[4,6]', '[14,32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(336, N'En finir avec les châtiments corporels à l’école', N'', N'R73P6-2', N'', N'Procédure spéciale', null, '[4,6]', '[14,32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(337, N'recueillir d’urgence des données détaillées sur la situation des enfants des rues et définir des mesures pratiques propres à assurer leur inclusion dans le système éducatif', N'', N'R74P1', N'', N'Procédure spéciale', null, '[4,6]', '[14,32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(338, N'concevoir et instituer, dans le souci de promouvoir la scolarisation des filles,  un système d’indicateurs permettant de déterminer les répercussions pour elles des travaux domestiques qu’elles effectuent', N'', N'R74P9', N'', N'Procédure spéciale', null, '[4,6]', '[14,32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(339, N'assurer à tous ses habitants la jouissance effective du droit à l’éducation.', N'', N'R73', N'', N'Procédure spéciale', null, '[4]', '[14]', null, Rapporteur spécial sur le droit à l’éducation, null, 'Non réalisé', '', 0, '', '', '', 2020),
(340, N'Appliquer la Charte nationale d’éducation et de formation et d’autres instruments juridiques, dont la Convention relative aux droits de l’enfant, et mener des politiques publiques concernant la couverture et la qualité de l’enseignement;', N'', N'R73P1', N'', N'Procédure spéciale', null, '[4]', '[14]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(341, N'Réduire le taux élevé d’abandon scolaire, avec 4 enfants sur 10 concernés dans l’enseignement primaire obligatoire, 5 sur 10 dans l’enseignement secondaire en milieu urbain et 8 sur 10 en milieu rural − selon les chiffres officiels;', N'', N'R73P3', N'', N'Procédure spéciale', null, '[4]', '[14]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(342, N'Étendre la couverture des programmes d’alphabétisation et élargir leur contenu au-delà du simple apprentissage de la lecture et de l’écriture;', N'', N'R73P4', N'', N'Procédure spéciale', null, '[4,7]', '[14,36]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(343, N'Evaluer la couverture et la portée des systèmes de prestations familiales en vue de procéder à brève échéance aux réformes voulues pour éviter que la scolarisation constitue un fardeau économique pour les familles ;', N'', N'R74P5', N'', N'Procédure spéciale', null, '[4]', '[14]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(344, N'suivre les recommandations du Parlement de l’enfant et de tenir compte de ses observations et propositions dans la conception des politiques éducatives nationales et régionales;', N'', N'R74P2', N'', N'Procédure spéciale', null, '[6]', '[32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(345, N'Mettre en place un système de centres et de refuges pour filles des zones
rurales victimes de violences;', N'', N'R74P13', N'', N'Procédure spéciale', null, '[6]', '[32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(346, N'Mettre au point des indicateurs désagrégés par sexe, condition sociale, origine ethnique et autres variables, sur l’abandon et l’absentéisme scolaires, en vue non seulement de réduire ces phénomènes mais d’amener tous les élèves au terme de leur scolarité, sans considération de sexe.', N'', N'R74P15', N'', N'Procédure spéciale', null, '[6]', '[32]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(347, N'Affecter des crédits à la fourniture ou au versement d’allocations pour l’achat de fauteuils roulants, de prothèses et autres moyens permettant à des enfants et adolescents− filles et garçons − démunis d’aller à l’école', N'', N'R74P12', N'', N'Procédure spéciale', null, '[6]', '[33]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(348, N'Faire des droits de l’homme une réalité dans la vie scolaire et un des principes fondamentaux de l’enseignement − comme le préconise la Charte nationale d’éducation et de formation − et en finir avec les châtiments corporels à l’école', N'', N'R73P6-1', N'', N'Procédure spéciale', null, '[7]', '[36]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(349, N'Mettre en place dès que possible les commissions appelées, aux niveaux central et régional, à assurer le suivi et l’évaluation des mesures adoptées dans le cadre du programme national d’éducation aux droits de l’homme, afin d’en adapter le contenu aux besoins des communautés nationales et de l’asseoir sur les instruments internationaux relatifs aux droits de l’homme', N'', N'R73P7', N'', N'Procédure spéciale', null, '[8]', '[]', null, Rapporteur spécial sur le droit à l’éducation, null, 'Réalisé', '', 100, '', '', '', 2020),
(350, N'Elargir le mandat du Bureau du Médiateur (Diwan Al Madhalim) afin qu’il
puisse exercer d’office des fonctions en matière de réalisation des droits économiques, sociaux et culturels, dont le droit à l’éducation', N'', N'R74P3', N'', N'Procédure spéciale', null, '[8]', '[]', null, Rapporteur spécial sur le droit à l’éducation, null, 'Réalisé', '', 100, '', '', '', 2020),
(351, N'De constituer une équipe interinstitutionnelle chargée de formuler et de mettre en œuvre les mesures nécessaires pour généraliser les cantines scolaires à échéance raisonnable', N'', N'R74P4', N'', N'Procédure spéciale', null, '[8]', '[]', null, Rapporteur spécial sur le droit à l’éducation, null, 'Réalisé', '', 100, '', '', '', 2020),
(352, N'Ancrer fermement les politiques publiques dans les droits de l’homme en vue de remédier aux asymétries et disparités sociales en matière de jouissance et d’exercice des droits par des actions positives adaptées aux besoins des groupes sociaux les plus défavorisés.', N'', N'R72', N'', N'Procédure spéciale', null, '[9]', '[]', null, Rapporteur spécial sur le droit à l’éducation, null, 'En cours', '', 30, '', '', '', 2020),
(353, N'Fournir l’effort en vue d’harmoniser et actualiser les dispositions des différentes réglementations, instructions administratives et lois pour les préciser et les fondre en un seul texte législatif', N'', N'R74P2', N'', N'Procédure spéciale', null, '[3]', '[10]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(354, N'adhérer aux deux Protocoles additionnels à la Convention des Nations Unies contre la criminalité transnationale organisée', N'', N'R87P1', N'', N'Procédure spéciale', null, '[2]', '[5]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(355, N'Adopter  des mesures visant à dispenser une formation au personnel qui a le pouvoir de mettre en détention, sur les aspects psychologiques de la détention, le respect de la culture de chacun et les procédures conformes au respect des droits de l’homme.', N'', N'R83P1', N'', N'Procédure spéciale', null, '[7]', '[36]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(356, N'-consolider les mécanismes de contrôle intérieur des fonctionnaires qui participent à la gestion de la migration et l’adoption de mesures et d’actions visant à combattre la corruption.', N'', N'R79', N'', N'Procédure spéciale', null, '[8]', '[]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'Réalisé', '', 100, '', '', '', 2020),
(357, N'Dispenser des cours de formation   pour ceux qui sont chargés des expulsions, afin qu’ils puissent s’acquitter de leurs fonctions dans le respect des droits et de la dignité des migrants.', N'', N'R83P2', N'', N'Procédure spéciale', null, '[7]', '[36]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'RC', '', 0, '', '', '', 2020),
(358, N'En ce qui concerne les institutions universitaires, la Rapporteuse spéciale les invite à continuer leurs efforts dans des programmes de recherche sur les droits des migrants.', N'', N'R90', N'', N'Procédure spéciale', null, '[7]', '[36]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'RC', '', 0, '', '', '', 2020),
(359, N'Encadrer Le phénomène de la migration, régulière et irrégulière dans une vision plus ample, qui n’envisage pas seulement une approche fondée sur le contrôle − à travers des mesures policières et répressives − mais aussi sur la protection des victimes de la migration socioéconomique et liée au développement
-Envisager un volet de contrôle des frontières ainsi qu’un volet d’intégration et de protection des populations migrantes et des programmes de réinsertion des migrants qui retournent, volontairement ou non, dans leur pays et ce pour construire une véritable politique et législation de la migration', N'', N'R75', N'', N'Procédure spéciale', null, '[8]', '[]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'Réalisé', '', 100, '', '', '', 2020),
(360, N'Faciliter l’accès aux mécanismes de recours pour les migrants par la sensibilisation et des campagnes d’information', N'', N'R79P2', N'', N'Procédure spéciale', null, '[7]', '[37]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'RC', '', 0, '', '', '', 2020),
(361, N'formulation d’un plan d’action pour la protection des droits des migrants à travers la formation des autorités judiciaires', N'', N'R79P1', N'', N'Procédure spéciale', null, '[7]', '[36]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(362, N'formuler de mesures claires visant à garantir que, au moment de son interpellation à la frontière ou sur le territoire national, en cas d’entrée ou de séjour irrégulier, un étranger soit toujours informé, au moins oralement et dans une langue qu’il comprend, de la nature et des motifs de la décision de refus d’entrée ou de séjour qu’on envisage de lui opposer.', N'', N'R80', N'', N'Procédure spéciale', null, '[6]', '[34]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'Réalisé', '', 100, '', '', '', 2020),
(363, N'fournir une protection et une aide suffisantes et suivre très attentivement la situation des mineurs non accompagnés.', N'', N'R81P3', N'', N'Procédure spéciale', null, '[6]', '[32,34]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(364, N'La création de centres de détention administrative envisagée dans le dispositif de la loi no 02-03 peut avoir des aspects positifs et négatifs. La création de ces centres doit être accompagnée de ressources financières adéquates pour leur établissement et leur gestion,  la formation du personnel, la garantie du respect des normes de vie et de séjour, ainsi que de mesures assurant la résolution rapide des cas individuels afin d’éviter des périodes de détention prolongées ou indéfinies. La Rapporteuse spéciale recommande aussi que ces centres soient conformes aux normes internationales établissant les garanties minimales pour les personnes mises en rétention. Elle rappelle à cet égard ses recommandations contenues dans le rapport E/CN.4/2003/85 et ses additifs et rectificatifs.', N'', N'R88', N'', N'Procédure spéciale', null, '[6,2,3]', '[34,7,10]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(365, N'La création de ces centres de détention administrative envisagée dans le dispositif de la loi no 02 03 doit être accompagnée de ressources financières adéquates pour leur établissement et leur gestion, la formation du personnel, la garantie du respect des normes de vie et de séjour, ainsi que de mesures assurant la résolution rapide des cas individuels afin d’éviter des périodes de détention prolongées ou indéfinies.', N'', N'R82P1', N'', N'Procédure spéciale', null, '[6,8]', '[34]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(366, N'La Rapporteuse spéciale juge essentielle la mise à jour de la législation nationale pour mieux gérer le problème de la migration irrégulière, qui comprend l’émigration des Marocains vers l’Europe et l’immigration de Subsahariens et ressortissants d’autres pays qui transitent par le Maroc vers l’Europe et qui souvent restent sur le territoire marocain illégalement', N'', N'R74P1', N'', N'Procédure spéciale', null, '[3]', '[9]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(367, N'La Rapporteuse spéciale recommande que la gestion des flux migratoires soit abordée dans un cadre de développement socioéconomique, par un renforcement de la contribution de l’UE aux efforts pour le développement d’un environnement social durable. 
-La Rapporteuse spéciale encourage l’UE à continuer son dialogue avec le Maroc et à fonder son partenariat sur des stratégies de coopération visant à combattre la migration irrégulière à travers des programmes d’assistance technique et de codéveloppement.', N'', N'R86', N'', N'Procédure spéciale', null, '[9]', '[]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'RC', '', 0, '', '', '', 2020),
(368, N'La Rapporteuse spéciale suggère aux ONG de renforcer leur position et d’adopter une approche plus orientée vers la protection des droits des migrants avec des campagnes de sensibilisation, des formes d’assistance matérielle et de soutien légal. Elle leur recommande de soutenir les migrants et de les associer à leur mandat pour qu’ils puissent participer à la défense de leurs droits.', N'', N'R89', N'', N'Procédure spéciale', null, '[7]', '[36]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'RC', '', 0, '', '', '', 2020),
(369, N'Les centres de détention administrative envisagée dans le dispositif de la loi no 02 03 doivent être conformes aux normes internationales établissant les garanties minimales pour les personnes mises en rétention', N'', N'R82P2', N'', N'Procédure spéciale', null, '[6,8]', '[34]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(370, N'Mettre en place de mesures en faveur des mineurs et des femmes enceintes qui, même s’ils sont candidats potentiels à l’expulsion, étant donné leur statut, ne peuvent être expulsés.', N'', N'R81P1', N'', N'Procédure spéciale', null, '[6,8]', '[30,32,34]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(371, N'Poursuivre les efforts pour remplir les obligations qui dérivent de la ratification de la Convention relative au statut des réfugiés et de la Convention régissant les aspects propres aux problèmes des réfugiés en Afriquepropres aux problèmes des réfugiés en Afrique.', N'', N'R76', N'', N'Procédure spéciale', null, '[9]', '[]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(372, N'poursuivre une politique migratoire visant à mettre fin à la dichotomie entre ce que le pays demande pour ses migrants à l’étranger en termes de protection et le degré de protection et d’assistance ainsi que le traitement qu’il offre aux migrants étrangers qui se trouvent au Maroc.', N'', N'R77', N'', N'Procédure spéciale', null, '[9]', '[]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(373, N'prendre conscience de la présence du phénomène de la prostitution et de l’exploitation des migrantes subsahariennes et à mettre en place des instruments adéquats visant la protection, l’assistance et la réhabilitation des victimes de la traite d’êtres humains.', N'', N'R78P2', N'', N'Procédure spéciale', null, '[6]', '[35]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(374, N'prendre des mesures de protection des droits des migrants irréguliers et de formes d’assistance spécifiques pour les migrants malades ou blessés et à prévoir des programmes pour leur réhabilitation physique et psychologique', N'', N'R78P1', N'', N'Procédure spéciale', null, '[6]', '[34]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'En cours', '', 30, '', '', '', 2020),
(375, N'veiller à ce que la législation n’autorise pas la détention d’enfants non accompagnés et que la détention d’enfants ne soit autorisée qu’en tant que mesure de dernier ressort et seulement dans l’intérêt supérieur de l’enfant', N'', N'R81P2', N'', N'Procédure spéciale', null, '[6,3]', '[34,32,9]', null, Rapporteuse spéciale sur les droits de l’homme des migrants, null, 'Réalisé', '', 100, '', '', '', 2020),
(376, N'La Rapporteuse spéciale invite instamment le Gouvernement marocain à ratifier la Convention de La Haye sur la protection des enfants et la coopération en matière d’adoption internationale et à l’adopter de toute urgence', N'(ز) تحث المقررة الخاصة حكومة المغرب على المسارعة إلى التصديق على اتفاقية لاهاي بشأن حماية الأطفال والتعاون في مجال التبني فيما بين البلدان', N'R167P7-1', N'ت.167.ف.7ج1', N'Procédure spéciale', null, '[2,6]', '[5,32]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'Non réalisé', '', 0, '', '', '', 2020),
(377, N'Nécessité d’entamer  des réformes tant législatives que politiques s’imposent au moins pour assurer la sécurité des enfants et leur accès à l’enseignement', N'ه‍) تثير حالة الطفلات الخادمات قلقاً كبيراً. ويجب إصلاح كل من التشريعات والسياسات، على الأقل لضمان سلامة الطفلات وحصولهن على التعليم.', N'R167P5-1', N'ت.167.ف.5.ج1', N'Procédure spéciale', null, '[3]', '[9]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'Réalisé', '', 100, '', '', '', 2020),
(378, N'Il faut examiner attentivement toute la législation, en particulier le droit pénal, pour que les enfants victimes de violences et d’exploitation ne soient pas pénalement responsables.
Il faut combler les lacunes de la loi qui découragent de porter plainte contre les auteurs de tels actes. Ainsi, en droit marocain, une fille qui porte plainte pour viol doit présenter au moins deux
témoins pour corroborer son récit et, si elle est enceinte et ne peut pas prouver qu’elle a été violée, s’expose à être accusée d’avoir eu des relations sexuelles interdites par la loi;', N'(د) ينبغي فحص جميع التشريعات، ولا سيما التشريعات الجنائية، عن كثب ضماناً لعدم تعريض الأطفال الذين يقعون ضحايا الإساءة والاستغلال للإدانة الجنائية. ويجب تصحيح نقائص القانون التي تثبط عن تقديم شكوى ضد المسيئين. فعلى سبيل المثال، يفرض القانون المغربي على الفتاة التي تدعي تعرضها للاغتصاب استقدام شاهدين على الأقل يؤيدان روايتها، فإذا كانت حاملاً وتعذر عليها إثبات تعرضها للاغتصاب فقد توجَّه إليها تهمة الجماع غير الشرعي؛', N'R167P4', N'ت.167.ف.4', N'Procédure spéciale', null, '[3,6]', '[9,32]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'En cours', '', 30, '', '', '', 2020),
(379, N'Nécessité d’entamer  des réformes tant législatives que politiques s’imposent au moins pour assurer la sécurité des enfants et leur accès à l’enseignement', N'ه‍) تثير حالة الطفلات الخادمات قلقاً كبيراً. ويجب إصلاح كل من التشريعات والسياسات، على الأقل لضمان سلامة الطفلات وحصولهن على التعليم.', N'R167P5-1', N'ت.167.ف.5.ج1', N'Procédure spéciale', null, '[4,3,6]', '[14,9,15,32]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'Réalisé', '', 100, '', '', '', 2020),
(380, N'Fournir plus grand effort est nécessaire dans le domaine de l’enseignement, en particulier dans les zones rurales les moins favorisées et qu’il faut résorber les disparités dans le taux de fréquentation scolaire entre les garçons et les filles', N'تضم المقررة الخاصة صوتها إلى لجنة حقوق الطفل التي أوصت ببذل المزيد من الجهود في مجال التعليم، ولا سيما في المناطق الريفية الأقل حظاً، وببذل جهود أيضاً تجاه تخفيض الفوارق القائمة في معدل الالتحاق بالمدارس بين البنين والبنات؛', N'R167P5-2', N'ت.167.ف.5.ج2', N'Procédure spéciale', null, '[4]', '[14]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'En cours', '', 30, '', '', '', 2020),
(381, N'Surveiller étroitement les endroits fréquentés par ces enfants non seulement pour pouvoir les aider mais aussi pour éloigner ceux qui pourraient abuser d’eux et les exploiter', N'(ب)ينبغي رصد أماكن تجمع الأطفال عن كثب، من أجل إغاثة الأطفال عند اللزوم ومن أجل ردع كل من تسول له نفسه استغلالهم؛', N'R167P2', N'ت.167.ف.2', N'Procédure spéciale', null, '[6]', '[32]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'En cours', '', 30, '', '', '', 2020),
(382, N'Examiner les possibilités de faire appel aux acteurs du secteur privé, en particulier au milieu des affaires, en qualité de partenaires dans la protection des enfants comme dans la promotion et le renforcement de leurs droits.', N'(ل) ينبغي تحري إمكانيات الاستعانة بمؤسسات القطاع الخاص، ولا سيما أوساط الأعمال، بوصفها شركاء في حماية الأطفال وفي تعزيز حقوقهم والنهوض بها.', N'R167P12', N'ت.167.ف.12', N'Procédure spéciale', null, '[6]', '[32]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'En cours', '', 30, '', '', '', 2020),
(383, N'étudier des solutions réalistes autres que le système d’adoption dit de la kafalah pour les enfants qu’aucun membre de leur famille ne désire accueillir', N'(ز) .... وينبغي أيضاً تحري بدائل عملية لنظام التبني بموجب الكفالة للأطفال الذين ليس لديهم أقرباء يرغبون في إيوائهم؛', N'R167P7-2', N'ت.167.ف.7ج2', N'Procédure spéciale', null, '[6]', '[32]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'Non réalisé', '', 0, '', '', '', 2020),
(384, N'Il faudrait que le Ministère du tourisme étudie sérieusement le problème des enfants qui travaillent comme "faux guides" à Marrakech et qui sont souvent arrêtés, mis à l’amende et emprisonnés et qu’il trouve des solutions à ce problème', N'(ح)  ينبغي لوزارة السياحة أن تنظر وتبحث بجدية في إيجاد حلول لمحنة الأطفال العاملين "كمرشدين سياحيين زائفين" في مراكش، وهم أطفال يتعرضون بصفة متكررة للتوقيف والتغريم والحبس؛', N'R167P8', N'ت.167.ف.8', N'Procédure spéciale', null, '[6]', '[32]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'En cours', '', 30, '', '', '', 2020),
(385, N'Il faudrait se pencher sur la question de l’entrée des filles dans la prostitution. Selon de très nombreuses informations, elles seraient de plus en plus dont beaucoup auraient commencé comme aides domestiques, à être emmenées à El Hajeb, dans le Moyen Atlas, où elles travailleraient comme prostituées', N'(ي) ينبغي إيلاء الاهتمام لمسألة استدراج الفتيات إلى البغاء. فهناك تقارير كثيرة تشير إلى أن عدداً متزايداً من الفتيات، ومنهن كثيرات بدأن العمل في الخدمة المنزلية، يُنقلن إلى مدينة الحاجب في الأطلس المتوسط، حيث يُجبرن على ممارسة البغاء؛', N'R167P10', N'ت.167.ف.10', N'Procédure spéciale', null, '[6]', '[32]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'Réalisé', '', 100, '', '', '', 2020),
(386, N'Bien qu’il n’existe pas de données sur la consommation de drogues dures par les enfants, il semble que la pratique qui consiste à renifler de la colle soit courante, en particulier chez les enfants des rues; cette pratique devrait donner lieu à des campagnes de sensibilisation et faire l’objet d’une surveillance', N'(ط) على الرغم من عدم وجود بيانات عن تعاطي الأطفال مخدرات قوية، يبدو أن استنشاق الغراء يشكل ظاهرة أخذة في الانتشار، وخاصة بين أطفال الشوارع، وينبغي أن تكون هدفاً لحملات التوعية والمراقبة؛', N'R167P9', N'ت.167.ف.9', N'Procédure spéciale', null, '[6]', '[32]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'En cours', '', 30, '', '', '', 2020),
(387, N'Réaliser des campagnes pour informer et sensibiliser la police et les autres responsables de l’application des lois quant aux moyens d’aborder efficacement le problème des enfants des rues sans les victimiser davantage', N'(أ) ينبغي إيلاء اهتمام عاجل لتزايد عدد أطفال الشوارع، وخاصة في المدن الكبيرة كالدار البيضاء ومراكش وطنجة. وفي هذا الصدد ينبغي توجيه حملات التثقيف والتوعية للشرطة وغيرها من وكالات إنفاذ القانون بغية تدريبها على سبل فعالة للتعامل مع أطفال الشوارع لا تعرضهم لمزيد من الأذية؛', N'R167P1-2', N'ت.167.ف.1', N'Procédure spéciale', null, '[7]', '[36]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'RC', '', 0, '', '', '', 2020),
(388, N'former et sensibiliser à l’écoute des enfants la police et les responsables de l’application des lois de façon à ce qu’ils ne se désintéressent pas d’eux au motif que, s’agissant uniquement de problèmes domestiques, leurs demandes ne relèvent pas de leur compétence', N'(ك) ينبغي إيجاد آليات استجابة تمكّن الأطفال من التماس المساعدة. وفي هذا الصدد، يجب تدريب أفراد الشرطة والموظفين المسؤولين عن إنفاذ القوانين وتوعيتهم بشأن الاستجابة للنداءات التي يوجهها الأطفال طلباً للمساعدة، وعدم تجاهلها باعتبارها خارجة عن مجال اختصاصهم عندما تتعلق بمسائل أسرية بحتة؛', N'R167P11', N'ت.167.ف.11', N'Procédure spéciale', null, '[7]', '[36]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'RC', '', 0, '', '', '', 2020),
(389, N'Il faudrait faire de l’éducation un instrument efficace pour ouvrir le débat sur des sujets considérés traditionnellement comme tabous, en particulier les atteintes sexuelles et la consommation de drogues. Il faudrait mobiliser non seulement les enfants mais également la population tout entière', N'و)  ينبغي استخدام التعليم كأداة فعالة لعرض ومناقشة المواضيع التي جرت العادة على اعتبارها من المحرمات، ولا سيما الإساءة الجنسية وتعاطي المخدرات. وينبغي أن تكون أنشطة الدعوة موجهة لا إلى الأطفال وحدهم وإنما إلى عموم الجمهور أيضاً؛', N'R167P6', N'ت.167.ف.6', N'Procédure spéciale', null, '[7]', '[36]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'RC', '', 0, '', '', '', 2020),
(390, N'lancer des programmes de sensibilisation afin d’informer le grand public, en particulier les enfants et les parents, des dangers très réels de l’émigration clandestine, que ce soit pendant le voyage ou une fois sur place', N'(ج) ينبغي التصدي لهجرة الأطفال سراً إلى الخارج، سواء أكانت طوعية أو قسرية. والقرب الجغرافي بين المغرب وإسبانيا يجعل الهجرة مشروعاً ممكناً يقدم عليه كثير من الأطفال. ويجب تنفيذ برامج تثقيف وتوعية لإعلام عموم الجمهور، ولا سيما الأطفال والآباء، بالمخاطر الجسام الكامنة في الهجرة غير المشروعة إلى الخارج، سواء في محاولة الهجرة نفسها أو في وجهتها؛', N'R167P3', N'ت.167.ف.3', N'Procédure spéciale', null, '[7]', '[37]', null, Rapporteuse spéciale chargée d'étudier la question de la vente d'enfants,
 de la prostitution des enfants et de la pornographie impliquant des enfants, null, 'RC', '', 0, '', '', '', 2020);

SET IDENTITY_INSERT Recommendations OFF
GO
-->>>>>>>>>’>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

INSERT INTO RecomOrgs (IdRecommendation, IdOrganisme, Date) values
(300, NaN, '2020-12-01'),
(301, NaN, '2020-12-01'),
(302, NaN, '2020-12-01'),
(303, NaN, '2020-12-01'),
(304, NaN, '2020-12-01'),
(305, NaN, '2020-12-01'),
(306, NaN, '2020-12-01'),
(306, NaN, '2020-12-01'),
(307, NaN, '2020-12-01'),
(307, NaN, '2020-12-01'),
(308, NaN, '2020-12-01'),
(308, NaN, '2020-12-01'),
(309, NaN, '2020-12-01'),
(309, NaN, '2020-12-01'),
(310, NaN, '2020-12-01'),
(310, NaN, '2020-12-01'),
(311, NaN, '2020-12-01'),
(311, NaN, '2020-12-01'),
(312, NaN, '2020-12-01'),
(312, NaN, '2020-12-01'),
(313, NaN, '2020-12-01'),
(313, NaN, '2020-12-01'),
(314, NaN, '2020-12-01'),
(314, NaN, '2020-12-01'),
(315, NaN, '2020-12-01'),
(316, NaN, '2020-12-01'),
(316, NaN, '2020-12-01'),
(316, NaN, '2020-12-01'),
(316, NaN, '2020-12-01'),
(317, NaN, '2020-12-01'),
(318, NaN, '2020-12-01'),
(319, NaN, '2020-12-01'),
(320, NaN, '2020-12-01'),
(321, NaN, '2020-12-01'),
(322, NaN, '2020-12-01'),
(323, NaN, '2020-12-01'),
(324, NaN, '2020-12-01'),
(325, NaN, '2020-12-01'),
(326, NaN, '2020-12-01'),
(326, NaN, '2020-12-01'),
(327, NaN, '2020-12-01'),
(327, NaN, '2020-12-01'),
(328, NaN, '2020-12-01'),
(328, NaN, '2020-12-01'),
(328, NaN, '2020-12-01'),
(328, NaN, '2020-12-01'),
(329, NaN, '2020-12-01'),
(329, NaN, '2020-12-01'),
(330, NaN, '2020-12-01'),
(330, NaN, '2020-12-01'),
(331, NaN, '2020-12-01'),
(331, NaN, '2020-12-01'),
(332, NaN, '2020-12-01'),
(332, NaN, '2020-12-01'),
(333, NaN, '2020-12-01'),
(334, NaN, '2020-12-01'),
(334, NaN, '2020-12-01'),
(335, NaN, '2020-12-01'),
(335, NaN, '2020-12-01'),
(336, NaN, '2020-12-01'),
(336, NaN, '2020-12-01'),
(337, NaN, '2020-12-01'),
(337, NaN, '2020-12-01'),
(338, NaN, '2020-12-01'),
(338, NaN, '2020-12-01'),
(339, NaN, '2020-12-01'),
(340, NaN, '2020-12-01'),
(341, NaN, '2020-12-01'),
(342, NaN, '2020-12-01'),
(343, NaN, '2020-12-01'),
(344, NaN, '2020-12-01'),
(344, NaN, '2020-12-01'),
(345, NaN, '2020-12-01'),
(346, NaN, '2020-12-01'),
(346, NaN, '2020-12-01'),
(347, NaN, '2020-12-01'),
(348, NaN, '2020-12-01'),
(348, NaN, '2020-12-01'),
(349, NaN, '2020-12-01'),
(350, NaN, '2020-12-01'),
(351, NaN, '2020-12-01'),
(352, NaN, '2020-12-01'),
(353, NaN, '2020-12-01'),
(353, NaN, '2020-12-01'),
(354, NaN, '2020-12-01'),
(354, NaN, '2020-12-01'),
(355, NaN, '2020-12-01'),
(355, NaN, '2020-12-01'),
(355, NaN, '2020-12-01'),
(356, NaN, '2020-12-01'),
(356, NaN, '2020-12-01'),
(356, NaN, '2020-12-01'),
(356, NaN, '2020-12-01'),
(356, NaN, '2020-12-01'),
(357, NaN, '2020-12-01'),
(357, NaN, '2020-12-01'),
(357, NaN, '2020-12-01'),
(358, NaN, '2020-12-01'),
(359, NaN, '2020-12-01'),
(359, NaN, '2020-12-01'),
(359, NaN, '2020-12-01'),
(360, NaN, '2020-12-01'),
(360, NaN, '2020-12-01'),
(360, NaN, '2020-12-01'),
(361, NaN, '2020-12-01'),
(361, NaN, '2020-12-01'),
(361, NaN, '2020-12-01'),
(362, NaN, '2020-12-01'),
(362, NaN, '2020-12-01'),
(362, NaN, '2020-12-01'),
(363, NaN, '2020-12-01'),
(363, NaN, '2020-12-01'),
(363, NaN, '2020-12-01'),
(363, NaN, '2020-12-01'),
(364, NaN, '2020-12-01'),
(364, NaN, '2020-12-01'),
(365, NaN, '2020-12-01'),
(366, NaN, '2020-12-01'),
(366, NaN, '2020-12-01'),
(367, NaN, '2020-12-01'),
(368, NaN, '2020-12-01'),
(368, NaN, '2020-12-01'),
(368, NaN, '2020-12-01'),
(369, NaN, '2020-12-01'),
(370, NaN, '2020-12-01'),
(370, NaN, '2020-12-01'),
(370, NaN, '2020-12-01'),
(370, NaN, '2020-12-01'),
(370, NaN, '2020-12-01'),
(370, NaN, '2020-12-01'),
(371, NaN, '2020-12-01'),
(371, NaN, '2020-12-01'),
(371, NaN, '2020-12-01'),
(372, NaN, '2020-12-01'),
(373, NaN, '2020-12-01'),
(373, NaN, '2020-12-01'),
(373, NaN, '2020-12-01'),
(373, NaN, '2020-12-01'),
(374, NaN, '2020-12-01'),
(374, NaN, '2020-12-01'),
(374, NaN, '2020-12-01'),
(375, NaN, '2020-12-01'),
(375, NaN, '2020-12-01'),
(375, NaN, '2020-12-01'),
(375, NaN, '2020-12-01'),
(375, NaN, '2020-12-01'),
(375, NaN, '2020-12-01'),
(376, NaN, '2020-12-01'),
(376, NaN, '2020-12-01'),
(377, NaN, '2020-12-01'),
(377, NaN, '2020-12-01'),
(377, NaN, '2020-12-01'),
(378, NaN, '2020-12-01'),
(379, NaN, '2020-12-01'),
(379, NaN, '2020-12-01'),
(379, NaN, '2020-12-01'),
(380, NaN, '2020-12-01'),
(381, NaN, '2020-12-01'),
(382, NaN, '2020-12-01'),
(382, NaN, '2020-12-01'),
(382, NaN, '2020-12-01'),
(383, NaN, '2020-12-01'),
(384, NaN, '2020-12-01'),
(385, NaN, '2020-12-01'),
(385, NaN, '2020-12-01'),
(385, NaN, '2020-12-01'),
(386, NaN, '2020-12-01'),
(387, NaN, '2020-12-01'),
(387, NaN, '2020-12-01'),
(387, NaN, '2020-12-01'),
(387, NaN, '2020-12-01'),
(388, NaN, '2020-12-01'),
(388, NaN, '2020-12-01'),
(388, NaN, '2020-12-01'),
(388, NaN, '2020-12-01'),
(388, NaN, '2020-12-01'),
(389, NaN, '2020-12-01'),
(390, NaN, '2020-12-01'),
(390, NaN, '2020-12-01');
