use crs
GO
SET IDENTITY_INSERT indicators ON
INSERT INTO indicators (id, hint ,id_noter_group ,name ,source_type ,type ,wa ,weight) VALUES
(1, NULL, 3, 'GNP growth rate (year n)','RangeNormalizer', 'Country', 0, 50.0),
(2, NULL, 3, 'GNP growth rate (year n+1)','RangeNormalizer', 'Country', 0, 35.0),
(3, NULL, 3, 'GNP growth rate (year n+2)','RangeNormalizer', 'Country', 0, 15.0),
(4, NULL, 5, 'Unemployment rate','RangeNormalizer', 'Country', 0, 100.0),
(5, NULL, 7, 'Annual inflation rate','RangeNormalizer', 'Country', 0, 60.0),
(6, NULL, 7, 'Global IPCH monthly index','RangeNormalizer', 'Country', 0, 40.0),
(7, NULL, 9, 'FDI (%GDP)','RangeNormalizer', 'Country', 0, 100.0),
(8, NULL, 11, 'Standard & Poor`s rating','MapNormalizer', 'Country', 0, 100.0),
(9, NULL, 13, 'Annual GNP per inhabitant (PPA)','RangeNormalizer', 'Country', 0, 100.0),
(10, NULL, 15, 'Inhabitants','RangeNormalizer', 'Country', 1, 100.0),
(11, NULL, 18, 'Domestic broadcasting rights (per year)','RangeNormalizer', 'Championship', 0, 45.0),
(12, 'Confederation : UEFA (Champions League ou Europa) | Coupe Libertadores etc.', 18, 'Confederation broadcasting rights (per year)','RangeNormalizer', 'Championship', 0, 15.0),
(13, NULL, 19, 'Credit rating of main broadcaster','MapNormalizer', 'Championship', 0, 15.0),
(14, NULL, 19, 'Equity of the broadcasting rights sharing system','RangeNormalizer', 'Championship', 0, 15.0),
(15, NULL, 19, 'Years of contracts to go','RangeNormalizer', 'Championship', 0, 10.0),
(16, NULL, 21, 'Supervisory body','MapNormalizer', 'Championship', 0, 50.0),
(17, NULL, 21, 'Quality of economic control','RangeNormalizer', 'Championship', 0, 50.0),
(18, NULL, 23, 'Average attendance last 3 seasons','RangeNormalizer', 'Championship', 0, 40.0),
(19, NULL, 23, 'Average attendance rate last 3 seasons','RangeNormalizer', 'Championship', 0, 40.0),
(20, NULL, 23, 'Trend','RangeNormalizer', 'Championship', 0, 20.0),
(21, NULL, 25, 'Number of teams in the league','RangeNormalizer', 'Championship', 0, 20.0),
(22, NULL, 25, 'Relegation risk','RangeNormalizer', 'Championship', 0, 40.0),
(23, NULL, 25, 'Points ratio top 25% teams / total teams','RangeNormalizer', 'Championship', 0, 40.0),
(24, NULL, 27, 'UEFA index by country (over 5 years)','RangeNormalizer', 'Championship', 0, 20.0),
(25, NULL, 28, 'Ratio: 1st club revenues vs 5th ','RangeNormalizer', 'Championship', 0, 30.0),
(26, NULL, 28, 'Transfermarkt value of championship','RangeNormalizer', 'Championship', 0, 50.0),
(27, NULL, 30, 'Transfer balance over 3 years ','RangeNormalizer', 'Championship', 0, 60.0),
(28, NULL, 30, 'Trend coefficient of the trading revenues','RangeNormalizer', 'Championship', 0, 20.0),
(29, NULL, 30, 'Total transfer transaction ','RangeNormalizer', 'Championship', 0, 20.0),
(30, NULL, 32, 'Club average revenue','RangeNormalizer', 'Championship', 0, 20.0),
(31, NULL, 33, 'Wage to turnover ratio','RangeNormalizer', 'Championship', 0, 20.0),
(32, NULL, 34, 'Net profit margin','RangeNormalizer', 'Championship', 0, 20.0),
(33, NULL, 35, 'Equity / Total Assets','RangeNormalizer', 'Championship', 0, 25.0),
(34, NULL, 36, 'Total debt / Total  assets','RangeNormalizer', 'Championship', 0, 15.0),
(35, NULL, 39, 'Ebitda growth','RangeNormalizer', 'Club', 1, 10.0),
(36, NULL, 40, 'Commercial & Matchday as % of revenue','RangeNormalizer', 'Club', 1, 10.0),
(37, NULL, 40, 'Revenue size','RangeNormalizer', 'Club', 1, 20.0),
(38, NULL, 41, 'Staff benefits (as a % of turnover)','RangeNormalizer', 'Club', 1, 20.0),
(39, NULL, 42, 'EBITDA margin (without trading) ','RangeNormalizer', 'Club', 1, 20.0),
(40, NULL, 42, 'Net result / revenues','RangeNormalizer', 'Club', 1, 20.0),
(41, NULL, 42, 'kkk','FunctionNormalizer', 'Club', 0, 1.0),
(42, NULL, 44, 'Trading profit / total revenues','FunctionNormalizer', 'Club', 1, 100.0),
(43, '(Equity / Total assets)', 46, 'Solvability ratio ','RangeNormalizer', 'Club', 0, 50.0),
(44, 'Financial debt/(Equity+Cash)', 46, 'Adjusted financial leverage','RangeNormalizer', 'Club', 0, 35.0),
(45, NULL, 47, 'Equity trend','RangeNormalizer', 'Club', 1, 15.0),
(46, 'Current asset / Current Liabilities', 49, 'Current ratio','RangeNormalizer', 'Club', 0, 40.0),
(47, 'Cash and cash equivalent / Current liabilities', 49, 'Acid test ratio','RangeNormalizer', 'Club', 0, 25.0),
(48, NULL, 50, '% short term debt','RangeNormalizer', 'Club', 0, 25.0),
(49, NULL, 51, 'Current ratio trend','RangeNormalizer', 'Club', 1, 5.0),
(50, NULL, 51, 'Acid test ratio trend','RangeNormalizer', 'Club', 1, 5.0),
(51, ' (Indebtedness / Total assets)', 53, 'Net debt to revenues','RangeNormalizer', 'Club', 0, 50.0),
(52, NULL, 53, 'Indebtedness ratio 2 (Ebitda /total debts)','RangeNormalizer', 'Club', 0, 35.0),
(53, NULL, 54, 'Financial debt trend','RangeNormalizer', 'Club', 1, 10.0),
(54, NULL, 54, 'Trading debt trend','RangeNormalizer', 'Club', 1, 5.0),
(55, NULL, 57, '% owned by main shareholder','RangeNormalizer', 'Club', 0, 15.0),
(56, NULL, 57, 'Quality of majority shareholder','MapNormalizer', 'Club', 0, 65.0),
(57, NULL, 58, 'Average number of years as a shareholder','RangeNormalizer', 'Club', 0, 20.0),
(58, NULL, 60, 'Quality of management ','RangeNormalizer', 'Club', 0, 35.0),
(59, NULL, 60, 'Quality of the Board','RangeNormalizer', 'Club', 0, 10.0),
(60, NULL, 60, 'Risk management policy','MapNormalizer', 'Club', 0, 10.0),
(61, NULL, 61, 'Quality of Auditor','MapNormalizer', 'Club', 0, 35.0),
(62, NULL, 61, 'Accounting standards','MapNormalizer', 'Club', 0, 10.0),
(63, NULL, 63, 'Club foundation','RangeNormalizer', 'Club', 0, 5.0),
(64, NULL, 64, 'Average ranking in the past 5 seasons','RangeNormalizer', 'Club', 0, 30.0),
(65, NULL, 64, 'Championship Winner','RangeNormalizer', 'Club', 0, 10.0),
(66, NULL, 64, 'Cup Winner','RangeNormalizer', 'Club', 0, 5.0),
(67, NULL, 65, '5 year UEFA index','RangeNormalizer', 'Club', 0, 35.0),
(68, NULL, 65, 'Champions League Winner','RangeNormalizer', 'Club', 0, 10.0),
(69, NULL, 65, 'Europa League Winner','RangeNormalizer', 'Club', 0, 5.0),
(70, NULL, 67, 'Number of year within the club','RangeNormalizer', 'Club', 0, 50.0),
(71, NULL, 67, 'Number of different coaches in the past 10 years','RangeNormalizer', 'Club', 0, 50.0),
(72, NULL, 69, 'Players with a professional contract','RangeNormalizer', 'Club', 0, 20.0),
(73, NULL, 69, 'Transfermarkt value of the team','RangeNormalizer', 'Club', 0, 80.0),
(74, NULL, 71, 'Number of Twitter followers','RangeNormalizer', 'Club', 0, 30.0),
(75, NULL, 71, 'Number of Facebook fans','RangeNormalizer', 'Club', 0, 30.0),
(76, NULL, 72, 'Average attendance in the last 3 seasons','RangeNormalizer', 'Club', 0, 30.0),
(77, NULL, 72, 'Average attendance rate in the last 3 seasons','RangeNormalizer', 'Club', 0, 10.0),
(78, NULL, 74, '% of First Team players coming from the Academy','RangeNormalizer', 'Club', 0, 20.0),
(79, NULL, 74, 'Academy CIES ranking','RangeNormalizer', 'Club', 0, 80.0),
(80, NULL, 76, 'Years to go of main sponsor','RangeNormalizer', 'Club', 0, 60.0),
(81, NULL, 77, 'Seniority of main sponsor','RangeNormalizer', 'Club', 0, 40.0),
(82, NULL, 79, 'Stadium owner','MapNormalizer', 'Club', 0, 30.0),
(83, NULL, 79, 'Stadium - If rental, duration of the lease agreement','MapNormalizer', 'Club', 0, 10.0),
(84, NULL, 79, 'Business seats / boxes','RangeNormalizer', 'Club', 0, 5.0),
(85, NULL, 79, 'Stadium last renovation / extension','RangeNormalizer', 'Club', 0, 20.0),
(86, NULL, 79, 'UEFA category','RangeNormalizer', 'Club', 0, 5.0),
(87, NULL, 80, 'Owner','MapNormalizer', 'Club', 0, 20.0),
(88, NULL, 80, 'If rental, duration of the lease agreement','MapNormalizer', 'Club', 0, 5.0),
(89, NULL, 80, 'Last renovation / extension','RangeNormalizer', 'Club', 0, 5.0),
(90, NULL, 82, 'Probity of the club','RangeNormalizer', 'Club', 0, 100.0),

SET IDENTITY_INSERT indicators OFF
GO