// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace apps.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "placeat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "sunt"
                        },
                        new
                        {
                            Id = 3,
                            Name = "suscipit"
                        },
                        new
                        {
                            Id = 4,
                            Name = "eum"
                        },
                        new
                        {
                            Id = 5,
                            Name = "aspernatur"
                        },
                        new
                        {
                            Id = 6,
                            Name = "in"
                        },
                        new
                        {
                            Id = 7,
                            Name = "impedit"
                        },
                        new
                        {
                            Id = 8,
                            Name = "in"
                        },
                        new
                        {
                            Id = 9,
                            Name = "minima"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ducimus"
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdRole");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sa@angular.io",
                            IdRole = 6,
                            ImageUrl = "",
                            IsActive = true,
                            Nom = "non",
                            Password = "123",
                            Profil = "nostrum"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Astride77@hotmail.fr",
                            IdRole = 2,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "soluta",
                            Password = "123",
                            Profil = "voluptatibus"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Marion.Garcia42@yahoo.fr",
                            IdRole = 4,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "voluptatem",
                            Password = "123",
                            Profil = "commodi"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Reybaud_Vidal@yahoo.fr",
                            IdRole = 8,
                            ImageUrl = "",
                            IsActive = true,
                            Nom = "veniam",
                            Password = "123",
                            Profil = "voluptas"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Denis.Renaud50@gmail.com",
                            IdRole = 9,
                            ImageUrl = "",
                            IsActive = true,
                            Nom = "fugit",
                            Password = "123",
                            Profil = "officia"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Samuel_Roux88@hotmail.fr",
                            IdRole = 4,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "assumenda",
                            Password = "123",
                            Profil = "voluptatem"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Berard_Leclerc@gmail.com",
                            IdRole = 8,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "non",
                            Password = "123",
                            Profil = "temporibus"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Edith.Remy@yahoo.fr",
                            IdRole = 10,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "eos",
                            Password = "123",
                            Profil = "et"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Esther_Colin47@hotmail.fr",
                            IdRole = 2,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "quia",
                            Password = "123",
                            Profil = "autem"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Althee.Leroux15@hotmail.fr",
                            IdRole = 9,
                            ImageUrl = "",
                            IsActive = true,
                            Nom = "ut",
                            Password = "123",
                            Profil = "soluta"
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.HasOne("Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
