// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace apps.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "repudiandae"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "sint"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "voluptatem"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "aperiam"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "quos"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "dolorum"
                        },
                        new
                        {
                            Id = 7,
                            Nom = "et"
                        },
                        new
                        {
                            Id = 8,
                            Nom = "voluptate"
                        },
                        new
                        {
                            Id = 9,
                            Nom = "fugiat"
                        },
                        new
                        {
                            Id = 10,
                            Nom = "provident"
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdRole");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "dj-m2x@hotmail.com",
                            IdRole = 7,
                            ImageUrl = "",
                            IsActive = true,
                            Nom = "voluptatem",
                            Password = "123",
                            Profil = "error"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Elsa_Lacroix32@hotmail.fr",
                            IdRole = 7,
                            ImageUrl = "",
                            IsActive = true,
                            Nom = "ut",
                            Password = "123",
                            Profil = "vel"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Alexine.Olivier68@yahoo.fr",
                            IdRole = 6,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "ab",
                            Password = "123",
                            Profil = "impedit"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Ferdinand75@gmail.com",
                            IdRole = 6,
                            ImageUrl = "",
                            IsActive = true,
                            Nom = "beatae",
                            Password = "123",
                            Profil = "doloremque"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Ambroise45@gmail.com",
                            IdRole = 6,
                            ImageUrl = "",
                            IsActive = true,
                            Nom = "voluptas",
                            Password = "123",
                            Profil = "quia"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Yolande_Fournier73@yahoo.fr",
                            IdRole = 6,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "dolores",
                            Password = "123",
                            Profil = "labore"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Salome19@hotmail.fr",
                            IdRole = 6,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "voluptas",
                            Password = "123",
                            Profil = "est"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Brice_Rousseau@yahoo.fr",
                            IdRole = 9,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "laboriosam",
                            Password = "123",
                            Profil = "saepe"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Abelin.Pierre32@yahoo.fr",
                            IdRole = 1,
                            ImageUrl = "",
                            IsActive = true,
                            Nom = "quia",
                            Password = "123",
                            Profil = "iusto"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Zephirin.Faure@hotmail.fr",
                            IdRole = 3,
                            ImageUrl = "",
                            IsActive = false,
                            Nom = "et",
                            Password = "123",
                            Profil = "eveniet"
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.HasOne("Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
